<?php

namespace App\Services\Architect\Contracts;

use App\Services\Architect\DTO\EngineResultDto;

interface EngineInterface
{
    /**
     * Run the engine compilation on the given state.
     *
     * @param array $state The active project state
     * @return EngineResultDto The compiled output DTO
     */
    public function run(array $state): EngineResultDto;

    /**
     * Validate the output generated by the run method.
     *
     * @param array $output The generated output to validate
     * @return array Structure: ['success' => bool, 'errors' => array, 'warnings' => array]
     */
    public function validate(array $output): array;

    /**
     * Get the identifier name of this engine.
     *
     * @return string
     */
    public function getName(): string;

    /**
     * Get the state keys this engine depends on.
     *
     * @return array List of state keys (e.g. ['projectName', 'requirements'])
     */
    public function getDependencies(): array;
}
