<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="AITOS Project Brief for {{ $projectName }} — generated by AITOS Context Compiler.">
    <title>{{ $projectName }} — Project Brief | AITOS</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Fira+Code:wght@400;500&display=swap" rel="stylesheet">
    <style>
        /* =========================================================
           RESET & ROOT TOKENS
        ========================================================= */
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

        :root {
            --navy:          #0f172a;
            --navy-mid:      #1e3a5f;
            --blue:          #2563eb;
            --blue-dim:      #3b82f6;
            --blue-light:    #dbeafe;
            --blue-xlight:   #eff6ff;
            --success:       #16a34a;
            --success-light: #dcfce7;
            --warning:       #ca8a04;
            --warning-light: #fef9c3;
            --danger:        #dc2626;
            --danger-light:  #fee2e2;
            --purple:        #7c3aed;
            --purple-light:  #ede9fe;
            --orange:        #ea580c;
            --orange-light:  #ffedd5;
            --bg:            #f1f5f9;
            --bg-mid:        #e8eef5;
            --surface:       #ffffff;
            --border:        #cbd5e1;
            --border-light:  #e2e8f0;
            --text:          #1e293b;
            --text-mid:      #334155;
            --text-muted:    #64748b;
            --r:             12px;
            --r-sm:          8px;
            --shadow:        0 1px 3px rgba(0,0,0,0.07), 0 4px 20px rgba(0,0,0,0.05);
        }

        html { font-size: 15px; scroll-behavior: smooth; }

        body {
            font-family: 'Inter', system-ui, -apple-system, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.7;
            -webkit-font-smoothing: antialiased;
        }

        /* =========================================================
           LAYOUT
        ========================================================= */
        .wrap { max-width: 1100px; margin: 0 auto; padding: 0 28px 80px; }

        /* =========================================================
           COVER PAGE
        ========================================================= */
        .cover {
            background: linear-gradient(145deg, #040d1e 0%, #0f2d54 35%, #1d3fa5 70%, #1e40af 100%);
            color: white;
            padding: 72px 64px 64px;
            margin: 0 -28px;
            position: relative;
            overflow: hidden;
        }

        /* Decorative circles */
        .cover::before, .cover::after { content: ''; position: absolute; border-radius: 50%; }
        .cover::before { width: 500px; height: 500px; background: rgba(255,255,255,0.03); top: -150px; right: -100px; }
        .cover::after  { width: 280px; height: 280px; background: rgba(255,255,255,0.04); bottom: -80px; left: -60px; }

        .cover-inner { position: relative; z-index: 1; }

        .cover-eyebrow {
            display: inline-flex;
            align-items: center;
            gap: 8px;
            background: rgba(255,255,255,0.1);
            border: 1px solid rgba(255,255,255,0.18);
            padding: 6px 18px;
            border-radius: 100px;
            font-size: 0.73rem;
            font-weight: 600;
            letter-spacing: 0.12em;
            text-transform: uppercase;
            color: rgba(255,255,255,0.85);
            margin-bottom: 32px;
        }

        .cover-title {
            font-size: clamp(2rem, 5vw, 3.6rem);
            font-weight: 900;
            line-height: 1.1;
            letter-spacing: -0.025em;
            margin-bottom: 18px;
            max-width: 780px;
        }

        .cover-goal {
            font-size: 1.1rem;
            color: rgba(255,255,255,0.72);
            max-width: 640px;
            margin-bottom: 36px;
            font-weight: 400;
            line-height: 1.65;
        }

        /* Stack badges on cover */
        .stack-row { display: flex; gap: 10px; flex-wrap: wrap; margin-bottom: 48px; }
        .stack-chip {
            background: rgba(255,255,255,0.1);
            border: 1px solid rgba(255,255,255,0.2);
            color: rgba(255,255,255,0.92);
            padding: 6px 18px;
            border-radius: 8px;
            font-size: 0.82rem;
            font-weight: 500;
        }

        /* Cover meta bar */
        .cover-meta {
            display: flex;
            gap: 40px;
            flex-wrap: wrap;
            padding-top: 28px;
            border-top: 1px solid rgba(255,255,255,0.12);
        }
        .meta-item { display: flex; flex-direction: column; gap: 3px; }
        .meta-label { font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.12em; color: rgba(255,255,255,0.45); font-weight: 600; }
        .meta-value { font-size: 0.88rem; color: rgba(255,255,255,0.88); font-weight: 500; }

        /* Stat pills on cover */
        .cover-stats { display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 32px; }
        .stat-pill {
            background: rgba(255,255,255,0.08);
            border: 1px solid rgba(255,255,255,0.14);
            padding: 10px 20px;
            border-radius: 10px;
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 2px;
            min-width: 80px;
        }
        .stat-num { font-size: 1.6rem; font-weight: 800; color: #93c5fd; line-height: 1; }
        .stat-lbl { font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.08em; color: rgba(255,255,255,0.5); font-weight: 500; }

        /* =========================================================
           SECTION CARDS
        ========================================================= */
        .section {
            background: var(--surface);
            border: 1px solid var(--border-light);
            border-radius: var(--r);
            box-shadow: var(--shadow);
            padding: 36px 40px;
            margin-top: 24px;
        }

        .section-hd {
            display: flex;
            align-items: flex-start;
            gap: 16px;
            margin-bottom: 28px;
            padding-bottom: 20px;
            border-bottom: 2px solid var(--border-light);
        }

        .sec-num {
            width: 38px; height: 38px;
            background: var(--blue);
            color: white;
            border-radius: 9px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: 800;
            font-size: 0.88rem;
            flex-shrink: 0;
            margin-top: 2px;
        }

        .sec-title { font-size: 1.2rem; font-weight: 800; color: var(--navy); line-height: 1.2; }
        .sec-sub   { font-size: 0.82rem; color: var(--text-muted); margin-top: 3px; }

        /* =========================================================
           METRICS GRID
        ========================================================= */
        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
            gap: 14px;
            margin-bottom: 28px;
        }

        .metric-card {
            background: var(--bg);
            border: 1px solid var(--border-light);
            border-radius: var(--r-sm);
            padding: 20px 16px;
            text-align: center;
        }

        .metric-val { font-size: 2.4rem; font-weight: 900; color: var(--blue); line-height: 1; margin-bottom: 6px; }
        .metric-lbl { font-size: 0.71rem; text-transform: uppercase; letter-spacing: 0.07em; color: var(--text-muted); font-weight: 600; }

        /* =========================================================
           SUMMARY BOX
        ========================================================= */
        .summary-box {
            background: var(--blue-xlight);
            border-left: 5px solid var(--blue);
            border-radius: 0 var(--r-sm) var(--r-sm) 0;
            padding: 20px 24px;
            font-size: 0.97rem;
            line-height: 1.85;
            color: var(--text-mid);
            margin-bottom: 28px;
        }

        /* =========================================================
           TABLES
        ========================================================= */
        .tbl-wrap { overflow-x: auto; border-radius: var(--r-sm); border: 1px solid var(--border-light); }

        table.dtbl {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.875rem;
        }

        .dtbl th {
            background: var(--bg);
            color: var(--text-mid);
            font-weight: 700;
            padding: 11px 16px;
            text-align: left;
            border-bottom: 2px solid var(--border);
            font-size: 0.72rem;
            text-transform: uppercase;
            letter-spacing: 0.06em;
            white-space: nowrap;
        }

        .dtbl td {
            padding: 10px 16px;
            border-bottom: 1px solid var(--border-light);
            color: var(--text);
            vertical-align: top;
        }

        .dtbl tr:last-child td { border-bottom: none; }
        .dtbl tr:hover td { background: #f8fafc; }
        .dtbl td code, .dtbl th code { font-family: 'Fira Code', monospace; font-size: 0.8rem; background: var(--bg); padding: 2px 7px; border-radius: 4px; color: var(--blue-dim); }

        /* =========================================================
           BADGES
        ========================================================= */
        .badge {
            display: inline-flex;
            align-items: center;
            padding: 3px 9px;
            border-radius: 100px;
            font-size: 0.7rem;
            font-weight: 700;
            letter-spacing: 0.04em;
            text-transform: uppercase;
            white-space: nowrap;
        }

        .b-get    { background: var(--blue-light);    color: #1d4ed8; }
        .b-post   { background: var(--success-light); color: #15803d; }
        .b-put    { background: var(--warning-light); color: #a16207; }
        .b-patch  { background: var(--purple-light);  color: #6d28d9; }
        .b-delete { background: var(--danger-light);  color: #b91c1c; }

        .b-pk     { background: #eff6ff; color: #1d4ed8; }
        .b-fk     { background: var(--orange-light); color: #9a3412; }
        .b-uk     { background: var(--purple-light); color: #6d28d9; }
        .b-null   { background: var(--bg); color: var(--text-muted); border: 1px solid var(--border); }
        .b-auto   { background: var(--success-light); color: #166534; }

        .b-high   { background: var(--danger-light);   color: #b91c1c; }
        .b-medium { background: var(--warning-light);  color: #a16207; }
        .b-low    { background: var(--success-light);  color: #15803d; }

        .b-p0 { background: #fee2e2; color: #7f1d1d; }
        .b-p1 { background: var(--danger-light); color: #b91c1c; }
        .b-p2 { background: var(--blue-light); color: #1d4ed8; }
        .b-p3 { background: var(--border-light); color: var(--text-muted); }

        /* Small text tag / chip */
        .chip {
            display: inline-block;
            background: var(--bg);
            border: 1px solid var(--border);
            color: var(--text-mid);
            padding: 3px 10px;
            border-radius: 6px;
            font-size: 0.76rem;
            font-weight: 500;
            margin: 2px 2px 2px 0;
        }

        /* =========================================================
           MERMAID / DIAGRAM
        ========================================================= */
        .diagram-wrap {
            background: var(--bg);
            border: 1px solid var(--border);
            border-radius: var(--r-sm);
            padding: 28px 20px;
            overflow-x: auto;
            text-align: center;
            min-height: 200px;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .diagram-wrap .mermaid { max-width: 100%; }
        .diagram-hint { text-align: center; font-size: 0.76rem; color: var(--text-muted); margin-top: 10px; }

        /* =========================================================
           ITEM LIST (bullet points)
        ========================================================= */
        .ilist {
            list-style: none;
            display: flex;
            flex-direction: column;
            gap: 7px;
        }

        .ilist li {
            display: flex;
            align-items: flex-start;
            gap: 10px;
            padding: 10px 14px;
            background: var(--bg);
            border-radius: var(--r-sm);
            border-left: 3px solid var(--blue);
            font-size: 0.9rem;
            line-height: 1.6;
            color: var(--text-mid);
        }

        .ilist li::before { content: '→'; color: var(--blue); font-weight: 700; flex-shrink: 0; margin-top: 1px; }

        .ilist.danger li  { border-left-color: var(--danger); }
        .ilist.danger li::before { color: var(--danger); content: '⚠'; }

        .ilist.success li { border-left-color: var(--success); }
        .ilist.success li::before { color: var(--success); content: '✓'; }

        .ilist.warn li    { border-left-color: var(--warning); }
        .ilist.warn li::before { color: var(--warning); content: '!'; }

        /* =========================================================
           USER STORY CARDS
        ========================================================= */
        .story-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(290px, 1fr));
            gap: 14px;
        }

        .story-card {
            background: var(--bg);
            border: 1px solid var(--border-light);
            border-radius: var(--r-sm);
            padding: 18px 20px;
            font-size: 0.875rem;
            color: var(--text-mid);
            font-style: italic;
            line-height: 1.7;
            position: relative;
        }

        .story-card::after {
            content: '"';
            font-size: 4rem;
            color: var(--blue);
            opacity: 0.12;
            position: absolute;
            bottom: -8px;
            right: 14px;
            font-family: Georgia, serif;
            line-height: 1;
        }

        /* =========================================================
           TWO-COLUMN LAYOUT
        ========================================================= */
        .two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }

        .col-box {
            background: var(--bg);
            border: 1px solid var(--border-light);
            border-radius: var(--r-sm);
            padding: 20px;
        }

        .col-box-title {
            font-size: 0.78rem;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.07em;
            color: var(--text-muted);
            padding-bottom: 12px;
            margin-bottom: 14px;
            border-bottom: 1px solid var(--border);
        }

        /* =========================================================
           PHASE TIMELINE
        ========================================================= */
        .timeline { display: flex; flex-direction: column; position: relative; }
        .timeline::before {
            content: '';
            position: absolute;
            left: 18px;
            top: 26px;
            bottom: 26px;
            width: 2px;
            background: var(--border);
        }

        .t-item { display: flex; align-items: flex-start; gap: 16px; padding: 12px 0; }

        .t-dot {
            width: 38px; height: 38px;
            background: var(--blue);
            color: white;
            border-radius: 50%;
            display: flex; align-items: center; justify-content: center;
            font-weight: 800; font-size: 0.82rem;
            flex-shrink: 0; z-index: 1;
            border: 3px solid var(--surface);
            box-shadow: 0 0 0 2px var(--blue);
        }

        .t-body { padding-top: 8px; }
        .t-text { font-size: 0.9rem; color: var(--text-mid); font-weight: 500; line-height: 1.5; }

        /* =========================================================
           RESOURCE BLOCKS (API)
        ========================================================= */
        .res-block { margin-bottom: 28px; padding-bottom: 28px; border-bottom: 1px solid var(--border-light); }
        .res-block:last-child { border-bottom: none; margin-bottom: 0; padding-bottom: 0; }

        .res-title {
            font-size: 0.95rem; font-weight: 700; color: var(--navy);
            margin-bottom: 12px;
            display: flex; align-items: center; gap: 10px; flex-wrap: wrap;
        }

        .res-title code {
            font-family: 'Fira Code', monospace;
            font-size: 0.85rem;
            background: var(--bg);
            padding: 4px 12px;
            border-radius: 6px;
            color: var(--blue-dim);
            font-weight: 500;
        }

        /* =========================================================
           TABLE SUBSECTION
        ========================================================= */
        .tbl-block { margin-bottom: 32px; }
        .tbl-block:last-child { margin-bottom: 0; }

        .tbl-name {
            display: flex; align-items: center; gap: 8px;
            font-size: 0.92rem; font-weight: 700; color: var(--navy);
            margin-bottom: 10px;
        }

        .tbl-name::before {
            content: '';
            display: inline-block;
            width: 4px; height: 18px;
            background: var(--blue);
            border-radius: 2px;
        }

        /* =========================================================
           SECTION SUB-HEADINGS
        ========================================================= */
        h4.sh {
            font-size: 0.78rem;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.07em;
            color: var(--text-muted);
            margin: 24px 0 12px;
        }

        h4.sh:first-child { margin-top: 0; }

        /* =========================================================
           BLUEPRINT RENDER
        ========================================================= */
        .bp-text {
            background: var(--bg);
            border: 1px solid var(--border-light);
            border-radius: var(--r-sm);
            padding: 20px 24px;
            font-size: 0.875rem;
            line-height: 1.8;
            color: var(--text-mid);
            white-space: pre-wrap;
            word-break: break-word;
            font-family: 'Fira Code', monospace;
            max-height: 400px;
            overflow-y: auto;
        }

        /* =========================================================
           FOOTER
        ========================================================= */
        .brief-footer {
            margin-top: 48px;
            background: var(--navy);
            color: rgba(255,255,255,0.65);
            padding: 28px 36px;
            border-radius: var(--r);
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-wrap: wrap;
            gap: 16px;
            font-size: 0.8rem;
        }

        .footer-brand { color: white; font-weight: 800; font-size: 1rem; margin-bottom: 4px; }

        /* =========================================================
           UTILITY
        ========================================================= */
        .mt-4  { margin-top: 16px; }
        .mt-6  { margin-top: 24px; }
        .empty { text-align: center; color: var(--text-muted); font-style: italic; padding: 32px; font-size: 0.875rem; }
        .mono  { font-family: 'Fira Code', monospace; font-size: 0.82rem; }
        .muted { color: var(--text-muted); }

        /* =========================================================
           PRINT STYLES
        ========================================================= */
        @media print {
            html { font-size: 12px; }
            body { background: white; }
            .wrap { max-width: 100%; padding: 0; }
            .cover { margin: 0; min-height: auto; padding: 40px 48px; }
            .section { box-shadow: none; border-radius: 0; page-break-inside: avoid; }
            .break-before { page-break-before: always; }
            .no-print { display: none !important; }
            .diagram-wrap { page-break-inside: avoid; min-height: auto; }
            .brief-footer { border-radius: 0; }
            .story-grid { grid-template-columns: 1fr 1fr; }
            .two-col { grid-template-columns: 1fr 1fr; }
            @page { margin: 1.8cm 1.5cm; size: A4; }
        }
    </style>
</head>
<body>
<div class="wrap">

{{-- ================================================================
     COVER PAGE
================================================================ --}}
@php
    $fw = $techStack['framework'] ?? ($projectModel['tech_stack']['framework'] ?? null);
    $db = $techStack['database']  ?? ($projectModel['tech_stack']['database']  ?? null);
    $fe = $techStack['frontend']  ?? ($projectModel['tech_stack']['frontend']  ?? null);

    $entityCount  = count($projectModel['entities']  ?? []);
    $moduleCount  = count($projectModel['modules']   ?? []);
    $tableCount   = count($databaseSchema['tables']  ?? []);
    $apiCount     = collect($apiDesign['resources']  ?? [])->sum(fn($r) => count($r['endpoints'] ?? []));
    $phaseCount   = count($projectPlan['development_order'] ?? $projectModel['phases'] ?? []);
    $ruleCount    = count($projectModel['business_rules'] ?? []);
@endphp

<div class="cover">
    <div class="cover-inner">
        <div class="cover-eyebrow">🤖 AITOS — AI Technical OS &nbsp;·&nbsp; Project Brief</div>

        <h1 class="cover-title">{{ $projectName }}</h1>

        @if($projectGoal)
            <p class="cover-goal">{{ $projectGoal }}</p>
        @elseif($projectDescription)
            <p class="cover-goal">{{ Str::limit($projectDescription, 250) }}</p>
        @endif

        {{-- Tech stack chips --}}
        @if($fw || $db || $fe)
        <div class="stack-row">
            @if($fw) <span class="stack-chip">⚙️ {{ ucfirst($fw) }}</span> @endif
            @if($db) <span class="stack-chip">🗄️ {{ ucfirst($db) }}</span> @endif
            @if($fe) <span class="stack-chip">🎨 {{ ucfirst($fe) }}</span> @endif
        </div>
        @endif

        {{-- Stat pills --}}
        <div class="cover-stats">
            @if($entityCount) <div class="stat-pill"><span class="stat-num">{{ $entityCount }}</span><span class="stat-lbl">Entities</span></div> @endif
            @if($moduleCount) <div class="stat-pill"><span class="stat-num">{{ $moduleCount }}</span><span class="stat-lbl">Modules</span></div> @endif
            @if($tableCount)  <div class="stat-pill"><span class="stat-num">{{ $tableCount }}</span><span class="stat-lbl">DB Tables</span></div> @endif
            @if($apiCount)    <div class="stat-pill"><span class="stat-num">{{ $apiCount }}</span><span class="stat-lbl">API Endpoints</span></div> @endif
            @if($phaseCount)  <div class="stat-pill"><span class="stat-num">{{ $phaseCount }}</span><span class="stat-lbl">Dev Phases</span></div> @endif
            @if($ruleCount)   <div class="stat-pill"><span class="stat-num">{{ $ruleCount }}</span><span class="stat-lbl">Business Rules</span></div> @endif
        </div>

        {{-- Meta bar --}}
        <div class="cover-meta">
            <div class="meta-item">
                <span class="meta-label">Generated</span>
                <span class="meta-value">{{ $generatedAt }}</span>
            </div>
            <div class="meta-item">
                <span class="meta-label">Tool</span>
                <span class="meta-value">AITOS Context Compiler</span>
            </div>
            <div class="meta-item">
                <span class="meta-label">Status</span>
                <span class="meta-value">Architecture Draft</span>
            </div>
            <div class="meta-item">
                <span class="meta-label">Submitted To</span>
                <span class="meta-value">Project Mentor / Reviewer</span>
            </div>
        </div>
    </div>
</div>{{-- /cover --}}


{{-- ================================================================
     SECTION 1 — EXECUTIVE SUMMARY
================================================================ --}}
@php
    $projectSummary = $requirements['projectSummary'] ?? $projectDescription ?? '';
@endphp

<div class="section break-before">
    <div class="section-hd">
        <div class="sec-num">1</div>
        <div>
            <div class="sec-title">Executive Summary</div>
            <div class="sec-sub">Project vision, goals, and key metrics at a glance</div>
        </div>
    </div>

    @if($projectSummary)
    <div class="summary-box">{{ $projectSummary }}</div>
    @endif

    {{-- Metrics row --}}
    <div class="metrics-grid">
        <div class="metric-card"><div class="metric-val">{{ $entityCount }}</div><div class="metric-lbl">Data Entities</div></div>
        <div class="metric-card"><div class="metric-val">{{ $moduleCount }}</div><div class="metric-lbl">Core Modules</div></div>
        <div class="metric-card"><div class="metric-val">{{ $tableCount }}</div><div class="metric-lbl">DB Tables</div></div>
        <div class="metric-card"><div class="metric-val">{{ $apiCount }}</div><div class="metric-lbl">API Endpoints</div></div>
        <div class="metric-card"><div class="metric-val">{{ $phaseCount }}</div><div class="metric-lbl">Dev Phases</div></div>
        <div class="metric-card"><div class="metric-val">{{ $ruleCount }}</div><div class="metric-lbl">Business Rules</div></div>
    </div>

    @if(!empty($projectModel['roles']))
    <h4 class="sh">User Roles</h4>
    <div>
        @foreach($projectModel['roles'] as $role)
            <span class="chip">👤 {{ $role }}</span>
        @endforeach
    </div>
    @endif

    @if(!empty($projectModel['modules']))
    <h4 class="sh mt-6">Core Modules</h4>
    <div>
        @foreach($projectModel['modules'] as $mod)
            <span class="chip">📦 {{ $mod }}</span>
        @endforeach
    </div>
    @endif
</div>


{{-- ================================================================
     SECTION 2 — ENTITY RELATIONSHIP DIAGRAM
================================================================ --}}
@if($mermaidDiagram || !empty($projectModel['entities']))
<div class="section">
    <div class="section-hd">
        <div class="sec-num">2</div>
        <div>
            <div class="sec-title">Entity Relationship Diagram</div>
            <div class="sec-sub">Visual data model — how system objects relate to each other</div>
        </div>
    </div>

    @if($mermaidDiagram)
    <div class="diagram-wrap">
        <div class="mermaid">{{ $mermaidDiagram }}</div>
    </div>
    <p class="diagram-hint no-print">💡 Diagram requires an internet connection to render (Mermaid.js CDN). Open in a browser, or print after it renders.</p>
    @endif

    @if(!empty($projectModel['entities']))
    <h4 class="sh mt-6">Entities Overview</h4>
    <div class="tbl-wrap">
    <table class="dtbl">
        <thead>
            <tr>
                <th>Entity</th>
                <th>Key Attributes</th>
                <th>Relationships</th>
            </tr>
        </thead>
        <tbody>
            @foreach($projectModel['entities'] as $entity)
            @php
                $eName  = is_array($entity) ? ($entity['name'] ?? '—') : $entity;
                $eAttrs = is_array($entity) ? ($entity['attributes'] ?? []) : [];
                $eRels  = array_filter($projectModel['relationships'] ?? [], function($r) use ($eName) {
                    return strcasecmp($r['from'] ?? '', $eName) === 0 || strcasecmp($r['to'] ?? '', $eName) === 0;
                });
            @endphp
            <tr>
                <td><strong>{{ $eName }}</strong></td>
                <td>
                    @forelse(array_slice($eAttrs, 0, 6) as $attr)
                        <code>{{ $attr }}</code>{{ !$loop->last ? ', ' : '' }}
                    @empty
                        <span class="muted">—</span>
                    @endforelse
                    @if(count($eAttrs) > 6) <span class="muted"> +{{ count($eAttrs) - 6 }} more</span> @endif
                </td>
                <td>
                    @forelse($eRels as $rel)
                        <span class="chip">{{ $rel['from'] }} → {{ $rel['to'] }} <em style="opacity:.6;">({{ $rel['type'] ?? 'rel' }})</em></span>
                    @empty
                        <span class="muted">—</span>
                    @endforelse
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    </div>
    @endif
</div>
@endif


{{-- ================================================================
     SECTION 3 — DATABASE SCHEMA
================================================================ --}}
@if(!empty($databaseSchema['tables']))
<div class="section break-before">
    <div class="section-hd">
        <div class="sec-num">3</div>
        <div>
            <div class="sec-title">Database Schema</div>
            <div class="sec-sub">Table definitions, column types, primary keys, foreign keys, and constraints</div>
        </div>
    </div>

    @foreach($databaseSchema['tables'] as $table)
    <div class="tbl-block">
        <div class="tbl-name">{{ strtoupper($table['name']) }}</div>
        <div class="tbl-wrap">
        <table class="dtbl">
            <thead>
                <tr><th>Column</th><th>Type</th><th>Constraints</th></tr>
            </thead>
            <tbody>
                @foreach($table['columns'] as $col)
                @php
                    $flags = [];
                    if ($col['primary_key']   ?? false) $flags[] = '<span class="badge b-pk">PK</span>';
                    if ($col['auto_increment'] ?? false) $flags[] = '<span class="badge b-auto">AUTO</span>';
                    if ($col['unique'] ?? false && !($col['primary_key'] ?? false)) $flags[] = '<span class="badge b-uk">UNIQUE</span>';
                    if ($col['nullable'] ?? false) $flags[] = '<span class="badge b-null">NULL</span>';
                    if (isset($col['foreign_key'])) {
                        $on = $col['foreign_key']['on'] ?? '?';
                        $ref = $col['foreign_key']['references'] ?? 'id';
                        $flags[] = "<span class=\"badge b-fk\">FK → {$on}.{$ref}</span>";
                    }
                @endphp
                <tr>
                    <td><code>{{ $col['name'] }}</code></td>
                    <td><span class="mono muted">{{ $col['type'] }}</span></td>
                    <td>{!! implode(' ', $flags) ?: '<span class="muted">—</span>' !!}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        </div>
    </div>
    @endforeach

    @if(!empty($databaseSchema['migration_order']))
    <h4 class="sh">Migration Order</h4>
    <div>
        @foreach($databaseSchema['migration_order'] as $i => $tbl)
            <span class="chip"><strong>{{ $i+1 }}.</strong> {{ $tbl }}</span>
        @endforeach
    </div>
    @endif
</div>
@endif


{{-- ================================================================
     SECTION 4 — API DESIGN
================================================================ --}}
@if(!empty($apiDesign['resources']))
<div class="section">
    <div class="section-hd">
        <div class="sec-num">4</div>
        <div>
            <div class="sec-title">API Design</div>
            <div class="sec-sub">REST resources, HTTP methods, paths, and middleware</div>
        </div>
    </div>

    @foreach($apiDesign['resources'] as $resource)
    <div class="res-block">
        <div class="res-title">
            Resource: <code>/api/{{ $resource['resource'] }}</code>
            @foreach($resource['middleware'] ?? [] as $mw)
                <span class="chip">{{ $mw }}</span>
            @endforeach
        </div>
        <div class="tbl-wrap">
        <table class="dtbl">
            <thead><tr><th width="72">Method</th><th>Path</th><th>Description</th></tr></thead>
            <tbody>
                @foreach($resource['endpoints'] as $ep)
                @php
                    $m = strtolower($ep['method'] ?? 'get');
                    $cls = match($m) {
                        'post'   => 'b-post',
                        'put'    => 'b-put',
                        'patch'  => 'b-patch',
                        'delete' => 'b-delete',
                        default  => 'b-get'
                    };
                @endphp
                <tr>
                    <td><span class="badge {{ $cls }}">{{ strtoupper($ep['method']) }}</span></td>
                    <td><code>{{ $ep['path'] }}</code></td>
                    <td>{{ $ep['description'] ?? '—' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        </div>
    </div>
    @endforeach

    @if(!empty($apiDesign['error_responses']))
    <h4 class="sh">Standard Error Responses</h4>
    <div>
        @foreach($apiDesign['error_responses'] as $code => $msg)
            <span class="chip"><strong>{{ $code }}</strong> — {{ $msg }}</span>
        @endforeach
    </div>
    @endif
</div>
@endif


{{-- ================================================================
     SECTION 5 — MODULE OWNERSHIP & PLANNING
================================================================ --}}
@if(!empty($projectPlan['module_ownership']) || !empty($projectModel['modules']))
<div class="section break-before">
    <div class="section-hd">
        <div class="sec-num">5</div>
        <div>
            <div class="sec-title">Module Ownership & Planning</div>
            <div class="sec-sub">Who owns what, complexity level, and delivery priority</div>
        </div>
    </div>

    @if(!empty($projectPlan['module_ownership']))
    <div class="tbl-wrap">
    <table class="dtbl">
        <thead>
            <tr>
                <th>Module</th>
                <th>Owner</th>
                <th>Role</th>
                <th>Complexity</th>
                <th>Priority</th>
            </tr>
        </thead>
        <tbody>
            @foreach($projectPlan['module_ownership'] as $mod)
            @php
                $comp = strtolower($mod['estimated_complexity'] ?? '');
                $compClass = str_contains($comp, 'high') ? 'b-high' : (str_contains($comp, 'medium') ? 'b-medium' : 'b-low');
                $prio = strtolower($mod['priority'] ?? '');
                $prioClass = str_contains($prio, 'p0') ? 'b-p0' : (str_contains($prio, 'p1') ? 'b-p1' : (str_contains($prio, 'p3') ? 'b-p3' : 'b-p2'));
            @endphp
            <tr>
                <td><strong>{{ $mod['module'] }}</strong></td>
                <td>{{ $mod['owner'] ?? '—' }}</td>
                <td><span class="chip">{{ $mod['role'] ?? '—' }}</span></td>
                <td><span class="badge {{ $compClass }}">{{ $mod['estimated_complexity'] ?? '—' }}</span></td>
                <td><span class="badge {{ $prioClass }}">{{ $mod['priority'] ?? '—' }}</span></td>
            </tr>
            @endforeach
        </tbody>
    </table>
    </div>
    @else
    <ul class="ilist">
        @foreach($projectModel['modules'] as $m)
        <li>{{ $m }}</li>
        @endforeach
    </ul>
    @endif

    @if(!empty($projectPlan['dependencies']))
    <h4 class="sh mt-6">Dependencies</h4>
    <ul class="ilist warn">
        @foreach($projectPlan['dependencies'] as $dep)
        <li>{{ $dep }}</li>
        @endforeach
    </ul>
    @endif
</div>
@endif


{{-- ================================================================
     SECTION 6 — IMPLEMENTATION ROADMAP
================================================================ --}}
@php
    $phases = $projectPlan['development_order'] ?? $projectModel['phases'] ?? [];
@endphp
@if(!empty($phases))
<div class="section">
    <div class="section-hd">
        <div class="sec-num">6</div>
        <div>
            <div class="sec-title">Implementation Roadmap</div>
            <div class="sec-sub">Development phases in sequential execution order</div>
        </div>
    </div>

    <div class="timeline">
        @foreach($phases as $i => $phase)
        <div class="t-item">
            <div class="t-dot">{{ $i + 1 }}</div>
            <div class="t-body"><div class="t-text">{{ $phase }}</div></div>
        </div>
        @endforeach
    </div>
</div>
@endif


{{-- ================================================================
     SECTION 7 — BUSINESS RULES & REQUIREMENTS
================================================================ --}}
@php
    $bizRules  = $projectModel['business_rules']              ?? [];
    $funcReqs  = $projectModel['functional_requirements']     ?? [];
    $nfReqs    = $projectModel['non_functional_requirements'] ?? [];
@endphp
@if(!empty($bizRules) || !empty($funcReqs) || !empty($nfReqs))
<div class="section break-before">
    <div class="section-hd">
        <div class="sec-num">7</div>
        <div>
            <div class="sec-title">Business Rules & Requirements</div>
            <div class="sec-sub">Domain constraints, functional specs, and non-functional expectations</div>
        </div>
    </div>

    @if(!empty($bizRules))
    <h4 class="sh">Business Rules</h4>
    <ul class="ilist">
        @foreach($bizRules as $rule)<li>{{ $rule }}</li>@endforeach
    </ul>
    @endif

    @if(!empty($funcReqs) || !empty($nfReqs))
    <div class="two-col mt-6">
        @if(!empty($funcReqs))
        <div class="col-box">
            <div class="col-box-title">✅ Functional Requirements</div>
            <ul class="ilist success">
                @foreach($funcReqs as $req)<li>{{ $req }}</li>@endforeach
            </ul>
        </div>
        @endif
        @if(!empty($nfReqs))
        <div class="col-box">
            <div class="col-box-title">⚡ Non-Functional Requirements</div>
            <ul class="ilist warn">
                @foreach($nfReqs as $req)<li>{{ $req }}</li>@endforeach
            </ul>
        </div>
        @endif
    </div>
    @endif
</div>
@endif


{{-- ================================================================
     SECTION 8 — USER STORIES
================================================================ --}}
@php
    $stories = $projectModel['user_stories'] ?? [];
@endphp
@if(!empty($stories))
<div class="section">
    <div class="section-hd">
        <div class="sec-num">8</div>
        <div>
            <div class="sec-title">User Stories</div>
            <div class="sec-sub">Feature expectations described from the end-user perspective</div>
        </div>
    </div>

    <div class="story-grid">
        @foreach($stories as $story)
        <div class="story-card">{{ $story }}</div>
        @endforeach
    </div>
</div>
@endif


{{-- ================================================================
     SECTION 9 — RISKS & ASSUMPTIONS
================================================================ --}}
@php
    $risks       = $projectModel['risks']       ?? [];
    $assumptions = $projectModel['assumptions'] ?? [];
@endphp
@if(!empty($risks) || !empty($assumptions))
<div class="section">
    <div class="section-hd">
        <div class="sec-num">9</div>
        <div>
            <div class="sec-title">Risks & Assumptions</div>
            <div class="sec-sub">Project uncertainties and baseline hypotheses for your mentor to review</div>
        </div>
    </div>

    <div class="two-col">
        @if(!empty($risks))
        <div class="col-box">
            <div class="col-box-title">⚠️ Identified Risks</div>
            <ul class="ilist danger">
                @foreach($risks as $r)<li>{{ $r }}</li>@endforeach
            </ul>
        </div>
        @endif
        @if(!empty($assumptions))
        <div class="col-box">
            <div class="col-box-title">💡 Assumptions</div>
            <ul class="ilist">
                @foreach($assumptions as $a)<li>{{ $a }}</li>@endforeach
            </ul>
        </div>
        @endif
    </div>
</div>
@endif


{{-- ================================================================
     SECTION 10 — ARCHITECTURE NOTES
================================================================ --}}
@php
    $aiNotes   = $projectModel['ai_notes'] ?? [];
    $techBp    = $blueprints['technical'] ?? '';
    $bizBp     = $blueprints['business']  ?? '';
@endphp
@if(!empty($aiNotes) || $techBp || $bizBp)
<div class="section break-before">
    <div class="section-hd">
        <div class="sec-num">10</div>
        <div>
            <div class="sec-title">Architecture Notes</div>
            <div class="sec-sub">AI-generated suggestions, technical blueprint, and business blueprint</div>
        </div>
    </div>

    @if(!empty($aiNotes))
    <h4 class="sh">AI Architecture Suggestions</h4>
    <ul class="ilist">
        @foreach($aiNotes as $note)<li>{{ $note }}</li>@endforeach
    </ul>
    @endif

    @if($techBp)
    <h4 class="sh mt-6">Technical Blueprint</h4>
    <div class="bp-text">{{ $techBp }}</div>
    @endif

    @if($bizBp)
    <h4 class="sh mt-6">Business Blueprint</h4>
    <div class="bp-text">{{ $bizBp }}</div>
    @endif
</div>
@endif


{{-- ================================================================
     FOOTER
================================================================ --}}
@php
    $enginesRun = count($pipelineReport['executed_engines'] ?? []);
    $dur        = round(($pipelineReport['duration_ms'] ?? 0) / 1000, 2);
    $warns      = count($pipelineReport['warnings'] ?? []);
    $errs       = count($pipelineReport['errors']   ?? []);
@endphp
<div class="brief-footer">
    <div>
        <div class="footer-brand">🤖 AITOS — AI Technical OS</div>
        <div>Context Compiler &nbsp;·&nbsp; Project Brief Generator &nbsp;·&nbsp; v1.5.0</div>
    </div>
    <div style="text-align:right;">
        <div style="color:white; font-weight:600;">{{ $projectName }}</div>
        <div>Generated {{ $generatedAt }}</div>
        <div style="margin-top:4px;">
            Pipeline: {{ $enginesRun }} engines · {{ $dur }}s
            @if($warns) · <span style="color:#fbbf24;">{{ $warns }} warnings</span> @endif
            @if($errs)  · <span style="color:#f87171;">{{ $errs }} errors</span>   @endif
        </div>
    </div>
</div>

</div>{{-- /wrap --}}

{{-- Mermaid.js — loaded from CDN, renders ER diagrams client-side --}}
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<script>
    mermaid.initialize({
        startOnLoad: true,
        theme: 'default',
        themeVariables: {
            primaryColor:       '#dbeafe',
            primaryTextColor:   '#1e3a5f',
            primaryBorderColor: '#93c5fd',
            lineColor:          '#64748b',
            secondaryColor:     '#f0fdf4',
            tertiaryColor:      '#fef9c3',
            fontSize:           '13px',
        },
        er: {
            diagramPadding: 20,
            layoutDirection: 'TB',
            minEntityWidth:  100,
            minEntityHeight: 70,
            entityPadding:   15,
            useMaxWidth:     true,
        }
    });
</script>
</body>
</html>
